# 14-2 呼び出し側ワークフロー
name: Call
on: pull_request
jobs:
  call:
    uses: ./.github/workflows/reusable-workflows.yml
    with: # 平文の入力パラメータ
      pr-number: ${{ github.event.pull_request.number }}
    secrets:  # シークレットの入力パラメータ
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
  print:
    needs: call
    runs-on: ubuntu-latest
    steps:
      - run: echo "Result> ${MESSAGE}"
        env:
          MESSAGE: ${{ needs.call.outputs.message }}
